version: "3.9"

services:
  app:
    image: dnabil/todolist-be
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_STRING=mysql://root:DBPASSWORD@tcp(db:3306)/todolist?charset=utf8mb4&parseTime=True&loc=Local
      - PORT=5555
      # - ENV JWT_TTL=5h
      # - ENV JWT_KEY=my-secret-key
    ports:
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todolist-be-network

  db:
    image: mariadb:11.2.2
    environment:
      - MARIADB_ROOT_PASSWORD=DBPASSWORD
      - MARIADB_DATABASE=todolist
    # volumes:
    # - <PATH>:/var/lib/mysql
    ports:
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      timeout: 10s
      retries: 15
    restart: on-failure
    networks:
      - todolist-be-network

networks:
  todolist-be-network:
