apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-todolistbe-autoscaler
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-todolistbe-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
